dependencies:
#      - name: zookeeper
#        repository: http://storage.googleapis.com/kubernetes-charts-incubator
#        version: 0.6.1

 #     - name: kafka
 #       repository: http://storage.googleapis.com/kubernetes-charts-incubator
 #       version: 0.4.3

  #    - name: postgresql
   #     repository: '@stable'
    #    version: 0.9.5
