apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "poke.fullname" . }}-api
  labels:
    app: {{ template "poke.name" . }}
    chart: {{ template "poke.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "poke.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "poke.name" . }}
        release: {{ .Release.Name }}
        component: api
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}-api
          image: {{ .Values.poke.api.image.repository }}
          tag: {{ .Values.poke.api.image.tag }}
          imagePullPolicy: {{ .Values.poke.api.image.pullPolicy }}
          command: ["/opt/bin/poke-api"]
          args: ["-Dplay.evolutions.db.default.autoApply=true"]
          envFrom:
            - configMapRef:
                name: api-configmap
          ports:
            - name: api
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9000
              initialDelaySeconds: 15
              periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 9000
              initialDelaySeconds: 5
              periodSeconds: 10