apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "poke.name" . }}-api
  labels:
    app: {{ template "poke.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: api
spec:
  rules:
  - host: api.poke.digital.local
  - http:
      paths:
      - path: /
        backend:
          serviceName: poke-api
          servicePort: 9000