apiVersion: v1
kind: ConfigMap
metadata:
  name: http-agent-configmap
  labels:
    app: {{ template "poke.name" . }}
    chart: {{ template "poke.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  BROKER: poke-kafka-0
  TOPIC: '{{ .Values.poke.topics.http }}'
  CONSUMER_GROUP: 'http-agent-consumer-group'
  HOST: 'kubernetes'
  ZONE: 'EU'