apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "poke.fullname" . }}-warp10
  labels:
    app: {{ template "poke.name" . }}
    chart: {{ template "poke.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: warp10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "poke.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "poke.name" . }}
        release: {{ .Release.Name }}
        component: warp10
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}-warp10
          image: {{ .Values.warp.image.repository }}
          tag: {{ .Values.warp.image.tag }}
          imagePullPolicy: {{ .Values.warp.image.pullPolicy }}
          command:
          - "/bin/bash"
          - "/tmp/warp-config/start.sh"
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
            - name: quantum
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
              initialDelaySeconds: 15
              periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
          volumeMounts:
          - mountPath: "/opt/warp/leveldb"
            name: leveldb
          - name: warp-config
            mountPath: /tmp/warp-config
      volumes:
      - name: leveldb
        persistentVolumeClaim:
          claimName: {{ template "poke.name" . }}-warp10
      - name: warp-config
        configMap:
          name: warp-configmap